spring:
  mail:
    host: live.smtp.mailtrap.io
    port: 587
    username: smtp@mailtrap.io
    password: 2101f5ec19f9798ae90eff32304f6b84
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8081